/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 编程语言
  C_Language: [{
    type: 'autogenerated',
    dirName: '计算机基础/编程语言/C_Language',
  }],
  CPP_Language: [{
    type: 'autogenerated',
    dirName: '计算机基础/编程语言/CPP_Language',
  }],

  // 数据结构与算法
  DSA_in_C: [{
    type: 'autogenerated',
    dirName: '计算机基础/数据结构与算法/DSA_in_C',
  }],

  // Web应用
  HTML: [{
    type: 'autogenerated',
    dirName: 'Web应用/HTML',
  }],

  CSS: [{
    type: 'autogenerated',
    dirName: 'Web应用/CSS',
  }],
  
  JavaScript: [{
    type: 'autogenerated',
    dirName: 'Web应用/JavaScript',
  }],
};

module.exports = sidebars;
